//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLBManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        /// <MetaDataID>{a1f92421-2f0c-4621-90d2-9be7b1fca569}</MetaDataID>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <MetaDataID>{f0827d1f-b127-497a-ba33-f69e6a3e677d}</MetaDataID>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <MetaDataID>{c2283ae0-173b-44f0-865e-d9116a9085d7}</MetaDataID>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <MetaDataID>{1aa0226a-3837-421b-adbf-b1fe7f6a4e1f}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLBManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <MetaDataID>{2856dbce-ab78-45bd-81db-c612ac0542a1}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add phone line.
        /// </summary>
        /// <MetaDataID>{e07e887e-1313-4702-82d8-e7e769a93213}</MetaDataID>
        public static string AddCallerIDLine
        {
            get
            {
                return ResourceManager.GetString("AddCallerIDLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Service Area.
        /// </summary>
        /// <MetaDataID>{cb8a84f6-b217-466f-ae2a-2a2d05874463}</MetaDataID>
        public static string AddServiceAreaHeader
        {
            get
            {
                return ResourceManager.GetString("AddServiceAreaHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Restaurant.
        /// </summary>
        /// <MetaDataID>{54efb1a7-a51c-4b21-9500-61961ecc8ff8}</MetaDataID>
        public static string AddServicesContextHeader
        {
            get
            {
                return ResourceManager.GetString("AddServicesContextHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        /// <MetaDataID>{a6bda03e-4ed6-489f-af3a-3cc13e13357e}</MetaDataID>
        public static string AdministrationTitle
        {
            get
            {
                return ResourceManager.GetString("AdministrationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assign  device.
        /// </summary>
        /// <MetaDataID>{86511faf-b65c-4558-b1a1-3de751af4730}</MetaDataID>
        public static string AssignPreparationDevicePrompt
        {
            get
            {
                return ResourceManager.GetString("AssignPreparationDevicePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier name :.
        /// </summary>
        /// <MetaDataID>{d310a4f0-cf82-4db0-b5dd-de7381b6f745}</MetaDataID>
        public static string CashierNameLabel
        {
            get
            {
                return ResourceManager.GetString("CashierNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashiers station.
        /// </summary>
        /// <MetaDataID>{d7e8ae34-4b91-481b-af68-0501df9e4864}</MetaDataID>
        public static string CashiersStationWindowTitle
        {
            get
            {
                return ResourceManager.GetString("CashiersStationWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Resources.
        /// </summary>
        /// <MetaDataID>{e86eced4-0c2e-488f-bc30-4f133e08f770}</MetaDataID>
        public static string CompanyResourcesLabel
        {
            get
            {
                return ResourceManager.GetString("CompanyResourcesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Title :.
        /// </summary>
        /// <MetaDataID>{d5cfe523-6ba7-4a55-bf5e-2b281536cf3a}</MetaDataID>
        public static string CompanyTitleLabel
        {
            get
            {
                return ResourceManager.GetString("CompanyTitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Room.
        /// </summary>
        /// <MetaDataID>{4d043295-2f56-4cae-9210-467c5e357eb2}</MetaDataID>
        public static string DefaultServiceAreaDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        /// <MetaDataID>{7a2e1d42-2c1c-46bc-b909-2ad42c9f5a6e}</MetaDataID>
        public static string DeliveryServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DeliveryServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        /// <MetaDataID>{3c1fa681-0ca5-4420-906f-a3ad2dba3602}</MetaDataID>
        public static string FisicalPartyAddressLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyAddressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        /// <MetaDataID>{945d8a0f-3737-4d3b-97cf-5059f2db9879}</MetaDataID>
        public static string FisicalPartyBranchLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyBranchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        /// <MetaDataID>{ab6b6e9e-c01e-41aa-ab72-2c0bc56d498e}</MetaDataID>
        public static string FisicalPartyCountryLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyCountryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier register to :.
        /// </summary>
        /// <MetaDataID>{63984b37-4c59-490c-872c-ea3393dbbe44}</MetaDataID>
        public static string FisicalPartyLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        /// <MetaDataID>{9673b82d-a853-476a-bed6-3dcc4a44a520}</MetaDataID>
        public static string FisicalPartyNameLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        /// <MetaDataID>{0faaa40d-b7a4-4da4-8187-5719a884d21b}</MetaDataID>
        public static string FisicalPartyVatNumberLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyVatNumberLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        /// <MetaDataID>{8aacc479-692b-49e8-91cf-ec87f2f8e740}</MetaDataID>
        public static string GraphicMenusTitle
        {
            get
            {
                return ResourceManager.GetString("GraphicMenusTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        /// <MetaDataID>{50872907-02dc-41ec-b24b-fe035965e530}</MetaDataID>
        public static string GraphicMenuTitle
        {
            get
            {
                return ResourceManager.GetString("GraphicMenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant tables.
        /// </summary>
        /// <MetaDataID>{2d699045-284a-41f0-94e6-56849df883ff}</MetaDataID>
        public static string HallServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("HallServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Headings.
        /// </summary>
        /// <MetaDataID>{513668ed-ba19-4470-a936-797ef19d7c83}</MetaDataID>
        public static string HeadingListViewTitle
        {
            get
            {
                return ResourceManager.GetString("HeadingListViewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On bill.
        /// </summary>
        /// <MetaDataID>{d7af3fb5-2fed-44cb-9d9e-0427bb5ef57f}</MetaDataID>
        public static string IsBilledtemStateDescription
        {
            get
            {
                return ResourceManager.GetString("IsBilledtemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item is paid.
        /// </summary>
        /// <MetaDataID>{3c7c3ac1-5cb2-4375-9da9-8bb6348f33d0}</MetaDataID>
        public static string ItemIsPaidCheckboxLabel
        {
            get
            {
                return ResourceManager.GetString("ItemIsPaidCheckboxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch CallerID Server.
        /// </summary>
        /// <MetaDataID>{e471a355-1acb-4c49-b5ec-a26f02afa991}</MetaDataID>
        public static string LaunchCallerIDServer
        {
            get
            {
                return ResourceManager.GetString("LaunchCallerIDServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        /// <MetaDataID>{9624cf84-8ee1-4cd5-a552-549592f7961b}</MetaDataID>
        public static string MenuItemsListActionsLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemsListActionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu makers.
        /// </summary>
        /// <MetaDataID>{809c4faa-413c-4af2-aa32-05a68f0e7b55}</MetaDataID>
        public static string MenuMakersTitle
        {
            get
            {
                return ResourceManager.GetString("MenuMakersTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu maker.
        /// </summary>
        /// <MetaDataID>{6565eea0-067f-4f81-93a8-c2c68830ca4f}</MetaDataID>
        public static string MenuMakerWindowTilte
        {
            get
            {
                return ResourceManager.GetString("MenuMakerWindowTilte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu taxes.
        /// </summary>
        /// <MetaDataID>{f4ee76e7-9031-43b7-8c2c-8ef3f293292f}</MetaDataID>
        public static string MenuTaxesWindowTitle
        {
            get
            {
                return ResourceManager.GetString("MenuTaxesWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New cashier desk.
        /// </summary>
        /// <MetaDataID>{2c482a4c-bbb3-45a5-9240-b26bd2227269}</MetaDataID>
        public static string NewCashierStationPrompt
        {
            get
            {
                return ResourceManager.GetString("NewCashierStationPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Menu Maker.
        /// </summary>
        /// <MetaDataID>{578117f0-8545-4db4-aae6-3b98b8633b06}</MetaDataID>
        public static string NewGraphicMenuDesignerMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("NewGraphicMenuDesignerMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        /// <MetaDataID>{5f92bdcb-1032-4284-8c04-fa7f491768cb}</MetaDataID>
        public static string NewGraphicMenuMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("NewGraphicMenuMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New preparation station.
        /// </summary>
        /// <MetaDataID>{51d7603e-8cb7-4ed6-be08-24492aa33bff}</MetaDataID>
        public static string NewPreparationStationPrompt
        {
            get
            {
                return ResourceManager.GetString("NewPreparationStationPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add equipment.
        /// </summary>
        /// <MetaDataID>{baed03d8-93c6-431a-9bad-434a93130a3b}</MetaDataID>
        public static string NewSubPreparationStationHeader
        {
            get
            {
                return ResourceManager.GetString("NewSubPreparationStationHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Translator.
        /// </summary>
        /// <MetaDataID>{5bf2035c-e41e-4759-8c50-30ecd85b3501}</MetaDataID>
        public static string NewTranslatorMenuPrompt
        {
            get
            {
                return ResourceManager.GetString("NewTranslatorMenuPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Waiter.
        /// </summary>
        /// <MetaDataID>{3a2a0f89-6ae5-4ff0-a41d-82f4d5b05996}</MetaDataID>
        public static string NewWaiterPrompt
        {
            get
            {
                return ResourceManager.GetString("NewWaiterPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        /// <MetaDataID>{2e2c19a9-33d5-4b73-8b6a-2aaa99a2d05e}</MetaDataID>
        public static string NoneItemStateDescription
        {
            get
            {
                return ResourceManager.GetString("NoneItemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On the road.
        /// </summary>
        /// <MetaDataID>{0bcd1f8c-7055-4dc1-9a6c-600e6997227e}</MetaDataID>
        public static string OnRoadtemStateDescription
        {
            get
            {
                return ResourceManager.GetString("OnRoadtemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        /// <MetaDataID>{d29705ef-9402-4413-8ea9-155031c2086d}</MetaDataID>
        public static string OpenGraphicMenuMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("OpenGraphicMenuMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        /// <MetaDataID>{b31fd0a0-9dc4-45df-a638-2d4a2b07afe5}</MetaDataID>
        public static string OrganizationMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("OrganizationMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On preparation.
        /// </summary>
        /// <MetaDataID>{140533ec-5c30-470d-b726-008873a38d0e}</MetaDataID>
        public static string PendingPreparationItemStateDescription
        {
            get
            {
                return ResourceManager.GetString("PendingPreparationItemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Food Preparation.
        /// </summary>
        /// <MetaDataID>{f1d07f20-21a5-4011-a14f-4ee033448c60}</MetaDataID>
        public static string PreparationSattionsTitle
        {
            get
            {
                return ResourceManager.GetString("PreparationSattionsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        /// <MetaDataID>{eaabbda3-65a5-4365-ba98-ed1cabce75ad}</MetaDataID>
        public static string PreparationStationDescriptionLabel
        {
            get
            {
                return ResourceManager.GetString("PreparationStationDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credential key.
        /// </summary>
        /// <MetaDataID>{9f41cc0d-29c4-4184-b23c-6546732d3c03}</MetaDataID>
        public static string PreparationStationIdentityLabel
        {
            get
            {
                return ResourceManager.GetString("PreparationStationIdentityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparation Station.
        /// </summary>
        /// <MetaDataID>{a8d3462b-80f7-4c5b-a7fa-ad954abd73c2}</MetaDataID>
        public static string PreparationStationWindowTitle
        {
            get
            {
                return ResourceManager.GetString("PreparationStationWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provided products.
        /// </summary>
        /// <MetaDataID>{685a5d67-f79e-47b9-9c8b-9c90b783f392}</MetaDataID>
        public static string ProvidedProductsTitle
        {
            get
            {
                return ResourceManager.GetString("ProvidedProductsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        /// <MetaDataID>{c489f6c0-64c7-4727-9b9d-ac2216672a2e}</MetaDataID>
        public static string RemoveCallerIDServer
        {
            get
            {
                return ResourceManager.GetString("RemoveCallerIDServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Restaurant.
        /// </summary>
        /// <MetaDataID>{725758ac-699d-41fb-ae2f-2cdc4fe2beb5}</MetaDataID>
        public static string RemoveServicesContextHeader
        {
            get
            {
                return ResourceManager.GetString("RemoveServicesContextHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Products &amp; Services.
        /// </summary>
        /// <MetaDataID>{44849575-9908-4630-860d-5458be65f692}</MetaDataID>
        public static string RestaurandProductsMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("RestaurandProductsMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        /// <MetaDataID>{081a56ce-8a20-47d1-8819-d830285c7c1a}</MetaDataID>
        public static string RestaurantMenusMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("RestaurantMenusMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Menu.
        /// </summary>
        /// <MetaDataID>{b9e3d717-cf76-4ddf-8d07-e355a5316caa}</MetaDataID>
        public static string SaveGraphicMenuMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("SaveGraphicMenuMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        /// <MetaDataID>{f23579c7-d298-48fd-b5f3-8dd946982eda}</MetaDataID>
        public static string SettingsMenuPrompt
        {
            get
            {
                return ResourceManager.GetString("SettingsMenuPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        /// <MetaDataID>{0a129bc9-da57-4785-b49e-875ca872a6c0}</MetaDataID>
        public static string TakeawayServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("TakeawayServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tax Authority :.
        /// </summary>
        /// <MetaDataID>{a10d68ff-92eb-4500-abd6-8c1e7b3a83c8}</MetaDataID>
        public static string TaxAuthoritySelectionLabel
        {
            get
            {
                return ResourceManager.GetString("TaxAuthoritySelectionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align Bottoms.
        /// </summary>
        /// <MetaDataID>{e0185679-f70e-4897-ab44-25d72abdfbaf}</MetaDataID>
        public static string ToolTipAlignBottoms
        {
            get
            {
                return ResourceManager.GetString("ToolTipAlignBottoms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align Lefts.
        /// </summary>
        /// <MetaDataID>{a5b3fac2-0cfe-4cbd-80cd-32cf07a2c864}</MetaDataID>
        public static string ToolTipAlignLefts
        {
            get
            {
                return ResourceManager.GetString("ToolTipAlignLefts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align Rights.
        /// </summary>
        /// <MetaDataID>{f3254f60-db8b-4fdd-b51d-db8ddcdbdf2b}</MetaDataID>
        public static string ToolTipAlignRights
        {
            get
            {
                return ResourceManager.GetString("ToolTipAlignRights", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align Tops.
        /// </summary>
        /// <MetaDataID>{e016ee53-305f-4003-9fd3-0e9853f18e13}</MetaDataID>
        public static string ToolTipAlignTops
        {
            get
            {
                return ResourceManager.GetString("ToolTipAlignTops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        /// <MetaDataID>{049e03ec-5806-419e-b716-02dacef29f12}</MetaDataID>
        public static string ToolTipBringFront
        {
            get
            {
                return ResourceManager.GetString("ToolTipBringFront", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Center Horizontally.
        /// </summary>
        /// <MetaDataID>{0463968b-bc75-41ce-b460-48c502132c27}</MetaDataID>
        public static string ToolTipCenterHorizontally
        {
            get
            {
                return ResourceManager.GetString("ToolTipCenterHorizontally", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Center Vertically.
        /// </summary>
        /// <MetaDataID>{562a128b-1ab3-40b2-8ec4-1db1aaae2097}</MetaDataID>
        public static string ToolTipCenterVertically
        {
            get
            {
                return ResourceManager.GetString("ToolTipCenterVertically", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        /// <MetaDataID>{d94f118b-77b6-4bb1-98a6-83e790546499}</MetaDataID>
        public static string ToolTipCopy
        {
            get
            {
                return ResourceManager.GetString("ToolTipCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        /// <MetaDataID>{b874b083-9b25-4b90-901e-dc665bf3835b}</MetaDataID>
        public static string ToolTipCut
        {
            get
            {
                return ResourceManager.GetString("ToolTipCut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        /// <MetaDataID>{b5308ec1-49e9-4bf3-8ec8-4ebb3e5926cd}</MetaDataID>
        public static string ToolTipDelete
        {
            get
            {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand Page Spacing.
        /// </summary>
        /// <MetaDataID>{bce575ec-c3c8-4e45-bada-2031b6c521ed}</MetaDataID>
        public static string ToolTipExpandLineSpace
        {
            get
            {
                return ResourceManager.GetString("ToolTipExpandLineSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grow fonts.
        /// </summary>
        /// <MetaDataID>{24f70ee6-19d2-41c4-ae8b-4b7bf42612c6}</MetaDataID>
        public static string ToolTipExpandPageFontsSizes
        {
            get
            {
                return ResourceManager.GetString("ToolTipExpandPageFontsSizes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Objects.
        /// </summary>
        /// <MetaDataID>{505988ed-96aa-45b8-bc60-8c21b00bfa09}</MetaDataID>
        public static string ToolTipGroupObjects
        {
            get
            {
                return ResourceManager.GetString("ToolTipGroupObjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make Horizontal Spacing Equal.
        /// </summary>
        /// <MetaDataID>{b12fef6b-74c7-4782-aa55-b0ace2ed6fbf}</MetaDataID>
        public static string ToolTipHorizontalSpacingEqual
        {
            get
            {
                return ResourceManager.GetString("ToolTipHorizontalSpacingEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        /// <MetaDataID>{59001515-923a-45e6-8cbd-b3413608734a}</MetaDataID>
        public static string ToolTipNew
        {
            get
            {
                return ResourceManager.GetString("ToolTipNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        /// <MetaDataID>{8a71f446-f357-4f74-bb3c-3f1b40d10428}</MetaDataID>
        public static string ToolTipOpen
        {
            get
            {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        /// <MetaDataID>{33e36afd-c6fc-47cd-8c4e-5b5996489cb9}</MetaDataID>
        public static string ToolTipPaste
        {
            get
            {
                return ResourceManager.GetString("ToolTipPaste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        /// <MetaDataID>{8673efe6-68ba-4f87-badc-52cc6bcff850}</MetaDataID>
        public static string ToolTipPrint
        {
            get
            {
                return ResourceManager.GetString("ToolTipPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        /// <MetaDataID>{b4ff3493-ac80-48c0-9d2e-f19c67f6514b}</MetaDataID>
        public static string ToolTipRedo
        {
            get
            {
                return ResourceManager.GetString("ToolTipRedo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Page Spacing.
        /// </summary>
        /// <MetaDataID>{5a519cda-bbf4-4807-8b1c-f663da5d2e58}</MetaDataID>
        public static string ToolTipResetLineSpace
        {
            get
            {
                return ResourceManager.GetString("ToolTipResetLineSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset fonts to Style defaults.
        /// </summary>
        /// <MetaDataID>{fade88e0-0bcd-4f05-9854-25d565469fcb}</MetaDataID>
        public static string ToolTipResetPageFontsSizes
        {
            get
            {
                return ResourceManager.GetString("ToolTipResetPageFontsSizes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        /// <MetaDataID>{7f280aae-561f-4f38-8c6d-2beb7baf750e}</MetaDataID>
        public static string ToolTipSave
        {
            get
            {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        /// <MetaDataID>{76d76e79-1294-486d-bce9-23d26967685c}</MetaDataID>
        public static string ToolTipSendBack
        {
            get
            {
                return ResourceManager.GetString("ToolTipSendBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shrink Page Spacing.
        /// </summary>
        /// <MetaDataID>{6d332bdd-8d94-490c-bc94-8f04a1f94766}</MetaDataID>
        public static string ToolTipShrinkLineSpace
        {
            get
            {
                return ResourceManager.GetString("ToolTipShrinkLineSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shrink fonts.
        /// </summary>
        /// <MetaDataID>{7a9b2909-7ed5-42f3-93d1-dd3f12e7d92d}</MetaDataID>
        public static string ToolTipShrinkPageFontsSizes
        {
            get
            {
                return ResourceManager.GetString("ToolTipShrinkPageFontsSizes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        /// <MetaDataID>{970333be-bc3d-4bf7-b92c-1a1cbd0053a7}</MetaDataID>
        public static string ToolTipUndo
        {
            get
            {
                return ResourceManager.GetString("ToolTipUndo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ungroup Objects.
        /// </summary>
        /// <MetaDataID>{467ba3a8-f382-430e-91b6-c41c541605b4}</MetaDataID>
        public static string ToolTipUngroupObjects
        {
            get
            {
                return ResourceManager.GetString("ToolTipUngroupObjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make Vertical Spacing Equal.
        /// </summary>
        /// <MetaDataID>{bd9ff7c6-ad0e-4b2b-8ba2-3d114609b97b}</MetaDataID>
        public static string ToolTipVerticalSpacingEqual
        {
            get
            {
                return ResourceManager.GetString("ToolTipVerticalSpacingEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        /// <MetaDataID>{ed10d801-f09b-4aed-8afb-5c4a84d43476}</MetaDataID>
        public static string TranslatorActivitiesLabel
        {
            get
            {
                return ResourceManager.GetString("TranslatorActivitiesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        /// <MetaDataID>{cd6f48a7-7a0b-4a69-9625-134d919d9fc4}</MetaDataID>
        public static string TranslatorEmailLabel
        {
            get
            {
                return ResourceManager.GetString("TranslatorEmailLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        /// <MetaDataID>{94bce00b-a491-4c89-93c1-51cce195cfa7}</MetaDataID>
        public static string TranslatorsTitle
        {
            get
            {
                return ResourceManager.GetString("TranslatorsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treasury.
        /// </summary>
        /// <MetaDataID>{e1cebb47-53d7-4b30-bc62-dad1874e7219}</MetaDataID>
        public static string TreasuryTitle
        {
            get
            {
                return ResourceManager.GetString("TreasuryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiters.
        /// </summary>
        /// <MetaDataID>{5fbceb16-53d8-4f5e-9b08-52acb1536b56}</MetaDataID>
        public static string WaitersTitle
        {
            get
            {
                return ResourceManager.GetString("WaitersTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write the company title.
        /// </summary>
        /// <MetaDataID>{6717063e-38ca-480b-9e63-8ae8bd551cc5}</MetaDataID>
        public static string WriteCompanyTitlePrompt
        {
            get
            {
                return ResourceManager.GetString("WriteCompanyTitlePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write  menu maker email.
        /// </summary>
        /// <MetaDataID>{319715de-7b1b-49ba-8266-c53e54da7368}</MetaDataID>
        public static string WriteMenuMakerEmailPrompt
        {
            get
            {
                return ResourceManager.GetString("WriteMenuMakerEmailPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write preparation statio description.
        /// </summary>
        /// <MetaDataID>{95a70dfe-9dd2-41e0-bf9f-bad6ffe5e8e0}</MetaDataID>
        public static string WritePreparationStationDescriptionPrompt
        {
            get
            {
                return ResourceManager.GetString("WritePreparationStationDescriptionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write  translator email.
        /// </summary>
        /// <MetaDataID>{56358c55-1063-4db4-bd3a-b8a4e3361827}</MetaDataID>
        public static string WriteTranslatorEmailPrompt
        {
            get
            {
                return ResourceManager.GetString("WriteTranslatorEmailPrompt", resourceCulture);
            }
        }
    }
}
