//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLBManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLBManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone line.
        /// </summary>
        public static string AddCallerIDLine {
            get {
                return ResourceManager.GetString("AddCallerIDLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Area.
        /// </summary>
        public static string AddServiceAreaHeader {
            get {
                return ResourceManager.GetString("AddServiceAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restaurant.
        /// </summary>
        public static string AddServicesContextHeader {
            get {
                return ResourceManager.GetString("AddServicesContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdministrationTitle {
            get {
                return ResourceManager.GetString("AdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign  courier device.
        /// </summary>
        public static string AssignCourierDevicePrompt {
            get {
                return ResourceManager.GetString("AssignCourierDevicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier Divice.
        /// </summary>
        public static string AssignCourierDeviceTitle {
            get {
                return ResourceManager.GetString("AssignCourierDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to register courier device.
        /// </summary>
        public static string AssignCourierDivecePrompt {
            get {
                return ResourceManager.GetString("AssignCourierDivecePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign  device.
        /// </summary>
        public static string AssignPreparationDevicePrompt {
            get {
                return ResourceManager.GetString("AssignPreparationDevicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier name :.
        /// </summary>
        public static string CashierNameLabel {
            get {
                return ResourceManager.GetString("CashierNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashiers station.
        /// </summary>
        public static string CashiersStationWindowTitle {
            get {
                return ResourceManager.GetString("CashiersStationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearItemsPreparationInfoMenuHeader {
            get {
                return ResourceManager.GetString("ClearItemsPreparationInfoMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Resources.
        /// </summary>
        public static string CompanyResourcesLabel {
            get {
                return ResourceManager.GetString("CompanyResourcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Title :.
        /// </summary>
        public static string CompanyTitleLabel {
            get {
                return ResourceManager.GetString("CompanyTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooked in.
        /// </summary>
        public static string CookingTimeSpanLabel {
            get {
                return ResourceManager.GetString("CookingTimeSpanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Room.
        /// </summary>
        public static string DefaultServiceAreaDescription {
            get {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Deliver Call Center.
        /// </summary>
        public static string DeliveryCallCenterStationsTitle {
            get {
                return ResourceManager.GetString("DeliveryCallCenterStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string DeliveryServicePointDescription {
            get {
                return ResourceManager.GetString("DeliveryServicePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FisicalPartyAddressLabel {
            get {
                return ResourceManager.GetString("FisicalPartyAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string FisicalPartyBranchLabel {
            get {
                return ResourceManager.GetString("FisicalPartyBranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string FisicalPartyCountryLabel {
            get {
                return ResourceManager.GetString("FisicalPartyCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier register to :.
        /// </summary>
        public static string FisicalPartyLabel {
            get {
                return ResourceManager.GetString("FisicalPartyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FisicalPartyNameLabel {
            get {
                return ResourceManager.GetString("FisicalPartyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string FisicalPartyVatNumberLabel {
            get {
                return ResourceManager.GetString("FisicalPartyVatNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string GraphicMenusTitle {
            get {
                return ResourceManager.GetString("GraphicMenusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string GraphicMenuTitle {
            get {
                return ResourceManager.GetString("GraphicMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant tables.
        /// </summary>
        public static string HallServicePointDescription {
            get {
                return ResourceManager.GetString("HallServicePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Headings.
        /// </summary>
        public static string HeadingListViewTitle {
            get {
                return ResourceManager.GetString("HeadingListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Delivery.
        /// </summary>
        public static string HomeDeliveryTreeNodeName {
            get {
                return ResourceManager.GetString("HomeDeliveryTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Delovery Settings.
        /// </summary>
        public static string HomeDeloveryServiceSettingsTitle {
            get {
                return ResourceManager.GetString("HomeDeloveryServiceSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On bill.
        /// </summary>
        public static string IsBilledtemStateDescription {
            get {
                return ResourceManager.GetString("IsBilledtemStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is paid.
        /// </summary>
        public static string ItemIsPaidCheckboxLabel {
            get {
                return ResourceManager.GetString("ItemIsPaidCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch CallerID Server.
        /// </summary>
        public static string LaunchCallerIDServer {
            get {
                return ResourceManager.GetString("LaunchCallerIDServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Home Delivery Service.
        /// </summary>
        public static string LaunchHomeDeliveryService {
            get {
                return ResourceManager.GetString("LaunchHomeDeliveryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MenuItemsListActionsLabel {
            get {
                return ResourceManager.GetString("MenuItemsListActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu makers.
        /// </summary>
        public static string MenuMakersTitle {
            get {
                return ResourceManager.GetString("MenuMakersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu maker.
        /// </summary>
        public static string MenuMakerWindowTilte {
            get {
                return ResourceManager.GetString("MenuMakerWindowTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu taxes.
        /// </summary>
        public static string MenuTaxesWindowTitle {
            get {
                return ResourceManager.GetString("MenuTaxesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cashier desk.
        /// </summary>
        public static string NewCashierStationPrompt {
            get {
                return ResourceManager.GetString("NewCashierStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Call Center Station.
        /// </summary>
        public static string NewDeliveryCallCenterStationPrompt {
            get {
                return ResourceManager.GetString("NewDeliveryCallCenterStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu Maker.
        /// </summary>
        public static string NewGraphicMenuDesignerMenuItemHeader {
            get {
                return ResourceManager.GetString("NewGraphicMenuDesignerMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        public static string NewGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("NewGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New preparation station.
        /// </summary>
        public static string NewPreparationStationPrompt {
            get {
                return ResourceManager.GetString("NewPreparationStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add equipment.
        /// </summary>
        public static string NewSubPreparationStationHeader {
            get {
                return ResourceManager.GetString("NewSubPreparationStationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New TakeAway POS.
        /// </summary>
        public static string NewTakeAwayStationPrompt {
            get {
                return ResourceManager.GetString("NewTakeAwayStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translator.
        /// </summary>
        public static string NewTranslatorMenuPrompt {
            get {
                return ResourceManager.GetString("NewTranslatorMenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Waiter.
        /// </summary>
        public static string NewWaiterPrompt {
            get {
                return ResourceManager.GetString("NewWaiterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneItemStateDescription {
            get {
                return ResourceManager.GetString("NoneItemStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the road.
        /// </summary>
        public static string OnRoadtemStateDescription {
            get {
                return ResourceManager.GetString("OnRoadtemStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        public static string OpenGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationMenuItemHeader {
            get {
                return ResourceManager.GetString("OrganizationMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On preparation.
        /// </summary>
        public static string PendingPreparationItemStateDescription {
            get {
                return ResourceManager.GetString("PendingPreparationItemStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PreparationStationDescriptionLabel {
            get {
                return ResourceManager.GetString("PreparationStationDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential key.
        /// </summary>
        public static string PreparationStationIdentityLabel {
            get {
                return ResourceManager.GetString("PreparationStationIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Preparation.
        /// </summary>
        public static string PreparationStationsTitle {
            get {
                return ResourceManager.GetString("PreparationStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Station.
        /// </summary>
        public static string PreparationStationWindowTitle {
            get {
                return ResourceManager.GetString("PreparationStationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared in.
        /// </summary>
        public static string PreparationTimeSpanLabel {
            get {
                return ResourceManager.GetString("PreparationTimeSpanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        public static string PriceListTitle {
            get {
                return ResourceManager.GetString("PriceListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided products.
        /// </summary>
        public static string ProvidedProductsTitle {
            get {
                return ResourceManager.GetString("ProvidedProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveCallerIDServer {
            get {
                return ResourceManager.GetString("RemoveCallerIDServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Restaurant.
        /// </summary>
        public static string RemoveServicesContextHeader {
            get {
                return ResourceManager.GetString("RemoveServicesContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products &amp; Services.
        /// </summary>
        public static string RestaurandProductsMenuItemHeader {
            get {
                return ResourceManager.GetString("RestaurandProductsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string RestaurantMenusMenuItemHeader {
            get {
                return ResourceManager.GetString("RestaurantMenusMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Menu.
        /// </summary>
        public static string SaveGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuPrompt {
            get {
                return ResourceManager.GetString("SettingsMenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        public static string TakeawayServicePointDescription {
            get {
                return ResourceManager.GetString("TakeawayServicePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Away.
        /// </summary>
        public static string TakeAwayStationsTitle {
            get {
                return ResourceManager.GetString("TakeAwayStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority :.
        /// </summary>
        public static string TaxAuthoritySelectionLabel {
            get {
                return ResourceManager.GetString("TaxAuthoritySelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottoms.
        /// </summary>
        public static string ToolTipAlignBottoms {
            get {
                return ResourceManager.GetString("ToolTipAlignBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Lefts.
        /// </summary>
        public static string ToolTipAlignLefts {
            get {
                return ResourceManager.GetString("ToolTipAlignLefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Rights.
        /// </summary>
        public static string ToolTipAlignRights {
            get {
                return ResourceManager.GetString("ToolTipAlignRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Tops.
        /// </summary>
        public static string ToolTipAlignTops {
            get {
                return ResourceManager.GetString("ToolTipAlignTops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        public static string ToolTipBringFront {
            get {
                return ResourceManager.GetString("ToolTipBringFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Horizontally.
        /// </summary>
        public static string ToolTipCenterHorizontally {
            get {
                return ResourceManager.GetString("ToolTipCenterHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Vertically.
        /// </summary>
        public static string ToolTipCenterVertically {
            get {
                return ResourceManager.GetString("ToolTipCenterVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ToolTipCopy {
            get {
                return ResourceManager.GetString("ToolTipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ToolTipCut {
            get {
                return ResourceManager.GetString("ToolTipCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Page Spacing.
        /// </summary>
        public static string ToolTipExpandLineSpace {
            get {
                return ResourceManager.GetString("ToolTipExpandLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow fonts.
        /// </summary>
        public static string ToolTipExpandPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipExpandPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Objects.
        /// </summary>
        public static string ToolTipGroupObjects {
            get {
                return ResourceManager.GetString("ToolTipGroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Horizontal Spacing Equal.
        /// </summary>
        public static string ToolTipHorizontalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipHorizontalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ToolTipNew {
            get {
                return ResourceManager.GetString("ToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolTipOpen {
            get {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ToolTipPaste {
            get {
                return ResourceManager.GetString("ToolTipPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ToolTipPrint {
            get {
                return ResourceManager.GetString("ToolTipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ToolTipRedo {
            get {
                return ResourceManager.GetString("ToolTipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Page Spacing.
        /// </summary>
        public static string ToolTipResetLineSpace {
            get {
                return ResourceManager.GetString("ToolTipResetLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset fonts to Style defaults.
        /// </summary>
        public static string ToolTipResetPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipResetPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        public static string ToolTipSendBack {
            get {
                return ResourceManager.GetString("ToolTipSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Page Spacing.
        /// </summary>
        public static string ToolTipShrinkLineSpace {
            get {
                return ResourceManager.GetString("ToolTipShrinkLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink fonts.
        /// </summary>
        public static string ToolTipShrinkPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipShrinkPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ToolTipUndo {
            get {
                return ResourceManager.GetString("ToolTipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Objects.
        /// </summary>
        public static string ToolTipUngroupObjects {
            get {
                return ResourceManager.GetString("ToolTipUngroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Vertical Spacing Equal.
        /// </summary>
        public static string ToolTipVerticalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipVerticalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string TranslatorActivitiesLabel {
            get {
                return ResourceManager.GetString("TranslatorActivitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string TranslatorEmailLabel {
            get {
                return ResourceManager.GetString("TranslatorEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string TranslatorsTitle {
            get {
                return ResourceManager.GetString("TranslatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury.
        /// </summary>
        public static string TreasuryTitle {
            get {
                return ResourceManager.GetString("TreasuryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiters.
        /// </summary>
        public static string WaitersTitle {
            get {
                return ResourceManager.GetString("WaitersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the company title.
        /// </summary>
        public static string WriteCompanyTitlePrompt {
            get {
                return ResourceManager.GetString("WriteCompanyTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write  menu maker email.
        /// </summary>
        public static string WriteMenuMakerEmailPrompt {
            get {
                return ResourceManager.GetString("WriteMenuMakerEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write preparation statio description.
        /// </summary>
        public static string WritePreparationStationDescriptionPrompt {
            get {
                return ResourceManager.GetString("WritePreparationStationDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write  translator email.
        /// </summary>
        public static string WriteTranslatorEmailPrompt {
            get {
                return ResourceManager.GetString("WriteTranslatorEmailPrompt", resourceCulture);
            }
        }
    }
}
