//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashierStationUI.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <MetaDataID>{a30051aa-8197-4a20-b5b4-da59b11e1add}</MetaDataID>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashierStationUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier name :.
        /// </summary>
        public static string CashierNameLabel
        {
            get
            {
                return ResourceManager.GetString("CashierNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashiers station.
        /// </summary>
        public static string CashiersStationWindowTitle
        {
            get
            {
                return ResourceManager.GetString("CashiersStationWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string DeliveryServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DeliveryServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FisicalPartyAddressLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyAddressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string FisicalPartyBranchLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyBranchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string FisicalPartyCountryLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyCountryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier register to :.
        /// </summary>
        public static string FisicalPartyLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FisicalPartyNameLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string FisicalPartyVatNumberLabel
        {
            get
            {
                return ResourceManager.GetString("FisicalPartyVatNumberLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant tables.
        /// </summary>
        public static string HallServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("HallServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On bill.
        /// </summary>
        public static string IsBilledtemStateDescription
        {
            get
            {
                return ResourceManager.GetString("IsBilledtemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item is paid.
        /// </summary>
        public static string ItemIsPaidCheckboxLabel
        {
            get
            {
                return ResourceManager.GetString("ItemIsPaidCheckboxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneItemStateDescription
        {
            get
            {
                return ResourceManager.GetString("NoneItemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On the road.
        /// </summary>
        public static string OnRoadtemStateDescription
        {
            get
            {
                return ResourceManager.GetString("OnRoadtemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to On preparation.
        /// </summary>
        public static string PendingPreparationItemStateDescription
        {
            get
            {
                return ResourceManager.GetString("PendingPreparationItemStateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveNode
        {
            get
            {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Takeaway.
        /// </summary>
        public static string TakeawayServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("TakeawayServicePointDescription", resourceCulture);
            }
        }
    }
}
