//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuItemsEditor.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <MetaDataID>{fc6e31f5-c599-44d7-b652-cd776d62cb34}</MetaDataID>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuItemsEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string AddCategoryMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("AddCategoryMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Magnitude Options.
        /// </summary>
        public static string AddMagnitudeOtionsGoupLabel
        {
            get
            {
                return ResourceManager.GetString("AddMagnitudeOtionsGoupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Option.
        /// </summary>
        public static string AddPreparationOtionLabel
        {
            get
            {
                return ResourceManager.GetString("AddPreparationOtionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Options group.
        /// </summary>
        public static string AddPreparationOtionsGoupLabel
        {
            get
            {
                return ResourceManager.GetString("AddPreparationOtionsGoupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Stepper Options group.
        /// </summary>
        public static string AddStepperOtionsGoupLabel
        {
            get
            {
                return ResourceManager.GetString("AddStepperOtionsGoupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Always appears in the item description.
        /// </summary>
        public static string AlwaysPartOfDescription
        {
            get
            {
                return ResourceManager.GetString("AlwaysPartOfDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change UncheckOption level property.
        /// </summary>
        public static string ChangeUncheckOptionPropertyValuePrompt
        {
            get
            {
                return ResourceManager.GetString("ChangeUncheckOptionPropertyValuePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow Custom.
        /// </summary>
        public static string CustomMenuItemCheckBoxLabel
        {
            get
            {
                return ResourceManager.GetString("CustomMenuItemCheckBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description .
        /// </summary>
        public static string DescriptionLabel
        {
            get
            {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditObject
        {
            get
            {
                return ResourceManager.GetString("EditObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change fixed scale type.
        /// </summary>
        public static string FixedScaleTypeEditMessage
        {
            get
            {
                return ResourceManager.GetString("FixedScaleTypeEditMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full name : .
        /// </summary>
        public static string FullNameLabel
        {
            get
            {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All options are recipe ingredient.
        /// </summary>
        public static string GroupOtionsIngredientCheckBoxLabel
        {
            get
            {
                return ResourceManager.GetString("GroupOtionsIngredientCheckBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide options group header.
        /// </summary>
        public static string HideOptionsGroupHeader
        {
            get
            {
                return ResourceManager.GetString("HideOptionsGroupHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is recipe ingredient.
        /// </summary>
        public static string IngredientCheckBoxLabel
        {
            get
            {
                return ResourceManager.GetString("IngredientCheckBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option participate  as ingredient in recipe of product.
        /// </summary>
        public static string IngredientCheckBoxToolTip
        {
            get
            {
                return ResourceManager.GetString("IngredientCheckBoxToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel
        {
            get
            {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ListAddButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ListAddButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ListDelButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ListDelButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string ListMoveDownButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ListMoveDownButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string ListMoveUpButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ListMoveUpButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ListRenameButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("ListRenameButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Magnitude Options .
        /// </summary>
        public static string MagnitudeOptionsGroupDefaultName
        {
            get
            {
                return ResourceManager.GetString("MagnitudeOptionsGroupDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meal course duration.
        /// </summary>
        public static string MealCourseDurationPrompt
        {
            get
            {
                return ResourceManager.GetString("MealCourseDurationPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string MealCourseListSetAsDefaultButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("MealCourseListSetAsDefaultButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Part of meals :.
        /// </summary>
        public static string MealPartLabel
        {
            get
            {
                return ResourceManager.GetString("MealPartLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meal Courses.
        /// </summary>
        public static string MealTypeCoursesListLabel
        {
            get
            {
                return ResourceManager.GetString("MealTypeCoursesListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Meal.
        /// </summary>
        public static string MealTypeDefaultName
        {
            get
            {
                return ResourceManager.GetString("MealTypeDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meal Types.
        /// </summary>
        public static string MealTypesListLabel
        {
            get
            {
                return ResourceManager.GetString("MealTypesListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string MemuEditorRootTreeNodeName
        {
            get
            {
                return ResourceManager.GetString("MemuEditorRootTreeNodeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuDefaultName
        {
            get
            {
                return ResourceManager.GetString("MenuDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string MenuItemDescriptionLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extras description :.
        /// </summary>
        public static string MenuItemExtrasDescriptionLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemExtrasDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu item full name :.
        /// </summary>
        public static string MenuItemFullNameLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemFullNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu item name :.
        /// </summary>
        public static string MenuItemNameLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MenuItemsListActionsLabel
        {
            get
            {
                return ResourceManager.GetString("MenuItemsListActionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Menu Item Type.
        /// </summary>
        public static string MenuItemTypeDefaultName
        {
            get
            {
                return ResourceManager.GetString("MenuItemTypeDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Menu item.
        /// </summary>
        public static string NewItemMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("NewItemMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string NewItemsCategoryName
        {
            get
            {
                return ResourceManager.GetString("NewItemsCategoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New menu.
        /// </summary>
        public static string NewMenuMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("NewMenuMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OptionGroupNameLabel
        {
            get
            {
                return ResourceManager.GetString("OptionGroupNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options group.
        /// </summary>
        public static string OptionGroupTitle
        {
            get
            {
                return ResourceManager.GetString("OptionGroupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option price progress.
        /// </summary>
        public static string OptionLevelPriceFactorPrompt
        {
            get
            {
                return ResourceManager.GetString("OptionLevelPriceFactorPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option name.
        /// </summary>
        public static string OptionNameLabel
        {
            get
            {
                return ResourceManager.GetString("OptionNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scale Type.
        /// </summary>
        public static string OptionScaleTypeLabel
        {
            get
            {
                return ResourceManager.GetString("OptionScaleTypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options group type.
        /// </summary>
        public static string OptionsGroupType
        {
            get
            {
                return ResourceManager.GetString("OptionsGroupType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options :.
        /// </summary>
        public static string OptionsLabel
        {
            get
            {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options Types :.
        /// </summary>
        public static string OptionsTypesLabel
        {
            get
            {
                return ResourceManager.GetString("OptionsTypesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Original Price.
        /// </summary>
        public static string OrgPriceLabel
        {
            get
            {
                return ResourceManager.GetString("OrgPriceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        public static string PredefinedTooltip
        {
            get
            {
                return ResourceManager.GetString("PredefinedTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options group.
        /// </summary>
        public static string PreparationOptionsGroupDefaultName
        {
            get
            {
                return ResourceManager.GetString("PreparationOptionsGroupDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t change uncheck option property. 
        ///You must check preparation options wich refered to this level.
        /// </summary>
        public static string PreparationOptionsGroupInvariantMessage
        {
            get
            {
                return ResourceManager.GetString("PreparationOptionsGroupInvariantMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string PreparationScaledOptionDefaultName
        {
            get
            {
                return ResourceManager.GetString("PreparationScaledOptionDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price context :.
        /// </summary>
        public static string PriceContextLabel
        {
            get
            {
                return ResourceManager.GetString("PriceContextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        public static string PriceLabel
        {
            get
            {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantitative.
        /// </summary>
        public static string QuantitativeCheckBoxLabel
        {
            get
            {
                return ResourceManager.GetString("QuantitativeCheckBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In the quantitative option, the first scaling level defines the option absence..
        /// </summary>
        public static string QuantitativeCheckBoxToolTip
        {
            get
            {
                return ResourceManager.GetString("QuantitativeCheckBoxToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sales Taxes :.
        /// </summary>
        public static string SaleTaxesLabel
        {
            get
            {
                return ResourceManager.GetString("SaleTaxesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New scale type.
        /// </summary>
        public static string ScaleTypeDefaultName
        {
            get
            {
                return ResourceManager.GetString("ScaleTypeDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New level.
        /// </summary>
        public static string ScaleTypeLevelDefaultName
        {
            get
            {
                return ResourceManager.GetString("ScaleTypeLevelDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scale Type Levels.
        /// </summary>
        public static string ScaleTypeLevelsListLabel
        {
            get
            {
                return ResourceManager.GetString("ScaleTypeLevelsListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scale Types.
        /// </summary>
        public static string ScaleTypesListLabel
        {
            get
            {
                return ResourceManager.GetString("ScaleTypesListLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scale Types.
        /// </summary>
        public static string ScaleTypesListWindowTitle
        {
            get
            {
                return ResourceManager.GetString("ScaleTypesListWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At Least one Selected.
        /// </summary>
        public static string SelectionTypeAtLeastOneSelectedDescription
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeAtLeastOneSelectedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product Selection.
        /// </summary>
        public static string SelectionTypeItemSelectionDescription
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeItemSelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection.
        /// </summary>
        public static string SelectionTypeMultiSelectionDescription
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeMultiSelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Simple Group.
        /// </summary>
        public static string SelectionTypeSimpleGroupDescription
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeSimpleGroupDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single Selection.
        /// </summary>
        public static string SelectionTypeSingleSelectionDescription
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeSingleSelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t check {0}.
        ///There are preaparation oprtions with wrang, scale type..
        /// </summary>
        public static string SelectionTypeViewModelCheckBoxPrompt
        {
            get
            {
                return ResourceManager.GetString("SelectionTypeViewModelCheckBoxPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sets this level as option initial level.
        /// </summary>
        public static string SetInitialOptionLevelTooltip
        {
            get
            {
                return ResourceManager.GetString("SetInitialOptionLevelTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show options types .
        /// </summary>
        public static string ShowCategoryOptionTypesMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("ShowCategoryOptionTypesMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step Options .
        /// </summary>
        public static string StepOptionsGroupName
        {
            get
            {
                return ResourceManager.GetString("StepOptionsGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stepper.
        /// </summary>
        public static string StepperCheckBoxLabel
        {
            get
            {
                return ResourceManager.GetString("StepperCheckBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string TaxesListBoxLabel
        {
            get
            {
                return ResourceManager.GetString("TaxesListBoxLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Taxes.
        /// </summary>
        public static string TaxesMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("TaxesMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit the scale types.
        /// </summary>
        public static string TooltipForEditScaleTypes
        {
            get
            {
                return ResourceManager.GetString("TooltipForEditScaleTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string TreeNodeRenameMenuItemHeader
        {
            get
            {
                return ResourceManager.GetString("TreeNodeRenameMenuItemHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uncheck preparation option sign.
        /// </summary>
        public static string UncheckOptionSignPrompt
        {
            get
            {
                return ResourceManager.GetString("UncheckOptionSignPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a description.
        /// </summary>
        public static string WriteDescriptionPrompt
        {
            get
            {
                return ResourceManager.GetString("WriteDescriptionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a description for extras.
        /// </summary>
        public static string WriteExtrasDescriptionPrompt
        {
            get
            {
                return ResourceManager.GetString("WriteExtrasDescriptionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a full name.
        /// </summary>
        public static string WriteFullNamePrompt
        {
            get
            {
                return ResourceManager.GetString("WriteFullNamePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a item name.
        /// </summary>
        public static string WriteItemNamePrompt
        {
            get
            {
                return ResourceManager.GetString("WriteItemNamePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a name.
        /// </summary>
        public static string WriteNamePrompt
        {
            get
            {
                return ResourceManager.GetString("WriteNamePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a full name.
        /// </summary>
        public static string WriteOptionFullNamePrompt
        {
            get
            {
                return ResourceManager.GetString("WriteOptionFullNamePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write a taxable type description.
        /// </summary>
        public static string WriteTaxableTypeDescriptionPrompt
        {
            get
            {
                return ResourceManager.GetString("WriteTaxableTypeDescriptionPrompt", resourceCulture);
            }
        }
    }
}
