//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone line.
        /// </summary>
        public static string Accent_Padding {
            get {
                return ResourceManager.GetString("Accent Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Padding.
        /// </summary>
        public static string AccentPaddingLabel {
            get {
                return ResourceManager.GetString("AccentPaddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone line.
        /// </summary>
        public static string AddCallerIDLine {
            get {
                return ResourceManager.GetString("AddCallerIDLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        public static string AddGraphicMenuLabel {
            get {
                return ResourceManager.GetString("AddGraphicMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service Area.
        /// </summary>
        public static string AddServiceAreaHeader {
            get {
                return ResourceManager.GetString("AddServiceAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Table.
        /// </summary>
        public static string AddServicePointHeader {
            get {
                return ResourceManager.GetString("AddServicePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restaurant.
        /// </summary>
        public static string AddServicesContextHeader {
            get {
                return ResourceManager.GetString("AddServicesContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdministrationTitle {
            get {
                return ResourceManager.GetString("AdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string AlignmentCenterPrompt {
            get {
                return ResourceManager.GetString("AlignmentCenterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string AlignmentLeftPrompt {
            get {
                return ResourceManager.GetString("AlignmentLeftPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string AlignmentRightPrompt {
            get {
                return ResourceManager.GetString("AlignmentRightPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount discount.
        /// </summary>
        public static string AmountDiscountLabel {
            get {
                return ResourceManager.GetString("AmountDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string BackgroundMenuTitle {
            get {
                return ResourceManager.GetString("BackgroundMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {blank}.
        /// </summary>
        public static string BlankItemName {
            get {
                return ResourceManager.GetString("BlankItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string BorderMenuTitle {
            get {
                return ResourceManager.GetString("BorderMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearItemsPriceInfoMenuHeader {
            get {
                return ResourceManager.GetString("ClearItemsPriceInfoMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Resources.
        /// </summary>
        public static string CompanyResourcesLabel {
            get {
                return ResourceManager.GetString("CompanyResourcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Title :.
        /// </summary>
        public static string CompanyTitleLabel {
            get {
                return ResourceManager.GetString("CompanyTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyMenuItemHeader {
            get {
                return ResourceManager.GetString("CopyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomLabel {
            get {
                return ResourceManager.GetString("CustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutMenuItemHeader {
            get {
                return ResourceManager.GetString("CutMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Room.
        /// </summary>
        public static string DefaultServiceAreaDescription {
            get {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string DefaultServicePointDescription {
            get {
                return ResourceManager.GetString("DefaultServicePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Menu.
        /// </summary>
        public static string DeleteGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuIHeadingHeader {
            get {
                return ResourceManager.GetString("DeleteMenuIHeadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Menu.
        /// </summary>
        public static string DesignGraphicMenuContextHeader {
            get {
                return ResourceManager.GetString("DesignGraphicMenuContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item info view .
        /// </summary>
        public static string DesignIteminfoVieMenuItemHeader {
            get {
                return ResourceManager.GetString("DesignIteminfoVieMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignMenuTitle {
            get {
                return ResourceManager.GetString("DesignMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Hall Layout.
        /// </summary>
        public static string DesignServiceAreaMenuContextHeader {
            get {
                return ResourceManager.GetString("DesignServiceAreaMenuContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuItemHeader {
            get {
                return ResourceManager.GetString("EditMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenuItemHeader {
            get {
                return ResourceManager.GetString("ExitMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st line.
        /// </summary>
        public static string ExtraDescriptionFollowNamePrompt {
            get {
                return ResourceManager.GetString("ExtraDescriptionFollowNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd line.
        /// </summary>
        public static string ExtraDescriptionInNewLinePrompt {
            get {
                return ResourceManager.GetString("ExtraDescriptionInNewLinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FilesMenuItemHeader {
            get {
                return ResourceManager.GetString("FilesMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string FontsMenuItemHeader {
            get {
                return ResourceManager.GetString("FontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item Description.
        /// </summary>
        public static string FoodItemDescriptionFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("FoodItemDescriptionFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item Extras.
        /// </summary>
        public static string FoodItemExtrasMenuItemHeader {
            get {
                return ResourceManager.GetString("FoodItemExtrasMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item Name.
        /// </summary>
        public static string FoodItemNameFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("FoodItemNameFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item Price.
        /// </summary>
        public static string FoodItemPriceMenuItemHeader {
            get {
                return ResourceManager.GetString("FoodItemPriceMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string FooItemAlignCenterPrompt {
            get {
                return ResourceManager.GetString("FooItemAlignCenterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string FooItemAlignLeftPrompt {
            get {
                return ResourceManager.GetString("FooItemAlignLeftPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string FooItemAlignRightPrompt {
            get {
                return ResourceManager.GetString("FooItemAlignRightPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &apos;{0}&apos;.
        /// </summary>
        public static string GraphicMenuDefaultLanguageLabel {
            get {
                return ResourceManager.GetString("GraphicMenuDefaultLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string GraphicMenuItemMoveDownMenuItemHeader {
            get {
                return ResourceManager.GetString("GraphicMenuItemMoveDownMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string GraphicMenuItemMoveUpMenuItemHeader {
            get {
                return ResourceManager.GetString("GraphicMenuItemMoveUpMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from menu.
        /// </summary>
        public static string GraphicMenuItemRemoveMenuItemHeader {
            get {
                return ResourceManager.GetString("GraphicMenuItemRemoveMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string GraphicMenuPreview {
            get {
                return ResourceManager.GetString("GraphicMenuPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string GraphicMenusTitle {
            get {
                return ResourceManager.GetString("GraphicMenusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string GraphicMenuTitle {
            get {
                return ResourceManager.GetString("GraphicMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall layout shape label.
        /// </summary>
        public static string HallLayoutLabelFontMenuItemHeader {
            get {
                return ResourceManager.GetString("HallLayoutLabelFontMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph heading.
        /// </summary>
        public static string HeadingFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("HeadingFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string HeadingListActionsLabel {
            get {
                return ResourceManager.GetString("HeadingListActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Headings.
        /// </summary>
        public static string HeadingListViewTitle {
            get {
                return ResourceManager.GetString("HeadingListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading Accents.
        /// </summary>
        public static string HeadingsAccentsMenuTitle {
            get {
                return ResourceManager.GetString("HeadingsAccentsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the overall line spacing within the food items and headings themselves (and also between them)..
        /// </summary>
        public static string ItemLineSpacingTooltipPrompt {
            get {
                return ResourceManager.GetString("ItemLineSpacingTooltipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the left indent for food item names to the specified value (has no effect on centered items)..
        /// </summary>
        public static string ItemNameIntentTooltipPrompt {
            get {
                return ResourceManager.GetString("ItemNameIntentTooltipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch CallerID Server.
        /// </summary>
        public static string LaunchCallerIDServer {
            get {
                return ResourceManager.GetString("LaunchCallerIDServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Options.
        /// </summary>
        public static string LayoutOptionsMenuTitle {
            get {
                return ResourceManager.GetString("LayoutOptionsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadding....
        /// </summary>
        public static string LoadingPrompt {
            get {
                return ResourceManager.GetString("LoadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the text of heading.
        /// </summary>
        public static string MenuHeadingTextPrompt {
            get {
                return ResourceManager.GetString("MenuHeadingTextPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu heading title :.
        /// </summary>
        public static string MenuHeadingTitleLabel {
            get {
                return ResourceManager.GetString("MenuHeadingTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item description :.
        /// </summary>
        public static string MenuItemDescriptionLabel {
            get {
                return ResourceManager.GetString("MenuItemDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string MenuItemEditDetails {
            get {
                return ResourceManager.GetString("MenuItemEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item extras :.
        /// </summary>
        public static string MenuItemExtrasLabel {
            get {
                return ResourceManager.GetString("MenuItemExtrasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item full title :.
        /// </summary>
        public static string MenuItemFullTitleLabel {
            get {
                return ResourceManager.GetString("MenuItemFullTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MenuItemsListActionsLabel {
            get {
                return ResourceManager.GetString("MenuItemsListActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items.
        /// </summary>
        public static string MenuItemsTitle {
            get {
                return ResourceManager.GetString("MenuItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item title :.
        /// </summary>
        public static string MenuItemTitleLabel {
            get {
                return ResourceManager.GetString("MenuItemTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Styles.
        /// </summary>
        public static string MenuStylesListLabel {
            get {
                return ResourceManager.GetString("MenuStylesListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Move.
        /// </summary>
        public static string MultiPriceHeadingsVerticalMoveLabel {
            get {
                return ResourceManager.GetString("MultiPriceHeadingsVerticalMoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi price spacing.
        /// </summary>
        public static string MultiPriceSpacingLabel {
            get {
                return ResourceManager.GetString("MultiPriceSpacingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New blank menu item.
        /// </summary>
        public static string NewBlankItemMenuItemHeader {
            get {
                return ResourceManager.GetString("NewBlankItemMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cashier desk.
        /// </summary>
        public static string NewCashierStationPrompt {
            get {
                return ResourceManager.GetString("NewCashierStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        public static string NewGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("NewGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Heading.
        /// </summary>
        public static string NewMenuIHeadingHeader {
            get {
                return ResourceManager.GetString("NewMenuIHeadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New preparation station.
        /// </summary>
        public static string NewPreparationStationPrompt {
            get {
                return ResourceManager.GetString("NewPreparationStationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pricelist.
        /// </summary>
        public static string NewPriceListMenuItemHeader {
            get {
                return ResourceManager.GetString("NewPriceListMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translator.
        /// </summary>
        public static string NewTranslatorMenuPrompt {
            get {
                return ResourceManager.GetString("NewTranslatorMenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Waiter.
        /// </summary>
        public static string NewWaiterPrompt {
            get {
                return ResourceManager.GetString("NewWaiterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Heading.
        /// </summary>
        public static string NormalHeadingFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("NormalHeadingFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        public static string OpenGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Margin.
        /// </summary>
        public static string PageMarginLabel {
            get {
                return ResourceManager.GetString("PageMarginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup.
        /// </summary>
        public static string PageSetupMenuItemHeader {
            get {
                return ResourceManager.GetString("PageSetupMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string ParagraphFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("ParagraphFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteMenuItemHeader {
            get {
                return ResourceManager.GetString("PasteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage discount.
        /// </summary>
        public static string PercentageDiscoundLabel {
            get {
                return ResourceManager.GetString("PercentageDiscoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Preparation.
        /// </summary>
        public static string PreparationSattionsTitle {
            get {
                return ResourceManager.GetString("PreparationSattionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PreparationStationDescriptionLabel {
            get {
                return ResourceManager.GetString("PreparationStationDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential key.
        /// </summary>
        public static string PreparationStationIdentityLabel {
            get {
                return ResourceManager.GetString("PreparationStationIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Heading Bottom Margin.
        /// </summary>
        public static string PriceHeadingBotomMarginLabel {
            get {
                return ResourceManager.GetString("PriceHeadingBotomMarginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Move.
        /// </summary>
        public static string PriceHeadingHorizontalMoveLabel {
            get {
                return ResourceManager.GetString("PriceHeadingHorizontalMoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle:.
        /// </summary>
        public static string PriceHeadingRotationAngleLabel {
            get {
                return ResourceManager.GetString("PriceHeadingRotationAngleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Price Heading.
        /// </summary>
        public static string PriceHeadingRotationLabel {
            get {
                return ResourceManager.GetString("PriceHeadingRotationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Heading Rotation Point.
        /// </summary>
        public static string PriceHeadingRotationPointLabel {
            get {
                return ResourceManager.GetString("PriceHeadingRotationPointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Display.
        /// </summary>
        public static string PriceLayoutDoNotDisplayPrompt {
            get {
                return ResourceManager.GetString("PriceLayoutDoNotDisplayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Description.
        /// </summary>
        public static string PriceLayoutFollowDescriptionPrompt {
            get {
                return ResourceManager.GetString("PriceLayoutFollowDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PriceLayoutNormalPrompt {
            get {
                return ResourceManager.GetString("PriceLayoutNormalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Description.
        /// </summary>
        public static string PriceLayoutWithDescriptionPrompt {
            get {
                return ResourceManager.GetString("PriceLayoutWithDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Name.
        /// </summary>
        public static string PriceLayoutWithNamePrompt {
            get {
                return ResourceManager.GetString("PriceLayoutWithNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra space near Item.
        /// </summary>
        public static string PriceLeaderExtraSpaceNearItemLabel {
            get {
                return ResourceManager.GetString("PriceLeaderExtraSpaceNearItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra space near Price.
        /// </summary>
        public static string PriceLeaderExtraSpaceNearPriceLabel {
            get {
                return ResourceManager.GetString("PriceLeaderExtraSpaceNearPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Dots Space.
        /// </summary>
        public static string PriceLeaderExtraSpaceOptionLabel {
            get {
                return ResourceManager.GetString("PriceLeaderExtraSpaceOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dots match Name color.
        /// </summary>
        public static string PriceLeaderMatchNameColorLabel {
            get {
                return ResourceManager.GetString("PriceLeaderMatchNameColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Leader.
        /// </summary>
        public static string PriceLeaderTypeSelectionLabel {
            get {
                return ResourceManager.GetString("PriceLeaderTypeSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pricelist.
        /// </summary>
        public static string PriceListPageTitle {
            get {
                return ResourceManager.GetString("PriceListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price location.
        /// </summary>
        public static string PriceLocationOptionsLabel {
            get {
                return ResourceManager.GetString("PriceLocationOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Options Details.
        /// </summary>
        public static string PriceOptionsDetailsPrompt {
            get {
                return ResourceManager.GetString("PriceOptionsDetailsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New price.
        /// </summary>
        public static string PriceOverrideLabel {
            get {
                return ResourceManager.GetString("PriceOverrideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price invisible.
        /// </summary>
        public static string PriceΙnvisibleLabel {
            get {
                return ResourceManager.GetString("PriceΙnvisibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided products.
        /// </summary>
        public static string ProvidedProductsTitle {
            get {
                return ResourceManager.GetString("ProvidedProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishMenuContextMenuHeader {
            get {
                return ResourceManager.GetString("PublishMenuContextMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoMenuItemHeader {
            get {
                return ResourceManager.GetString("RedoMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveCallerIDServer {
            get {
                return ResourceManager.GetString("RemoveCallerIDServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Menu.
        /// </summary>
        public static string RemoveGraphicMenuContextHeader {
            get {
                return ResourceManager.GetString("RemoveGraphicMenuContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service Area.
        /// </summary>
        public static string RemoveServiceAreaHeader {
            get {
                return ResourceManager.GetString("RemoveServiceAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Restaurant.
        /// </summary>
        public static string RemoveServicesContextHeader {
            get {
                return ResourceManager.GetString("RemoveServicesContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameMenuIHeadingHeader {
            get {
                return ResourceManager.GetString("RenameMenuIHeadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string RestaurantMenusMenuItemHeader {
            get {
                return ResourceManager.GetString("RestaurantMenusMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Menu.
        /// </summary>
        public static string SaveGraphicMenuMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveGraphicMenuMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuPrompt {
            get {
                return ResourceManager.GetString("SettingsMenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show multiple prices.
        /// </summary>
        public static string ShowMultiplePricesCheboxLabel {
            get {
                return ResourceManager.GetString("ShowMultiplePricesCheboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] StylePrototype {
            get {
                object obj = ResourceManager.GetObject("StylePrototype", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleSheet Accents .
        /// </summary>
        public static string StyleSheetAccentsMenuTitle {
            get {
                return ResourceManager.GetString("StyleSheetAccentsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string StyleSheetLabel {
            get {
                return ResourceManager.GetString("StyleSheetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Style).
        /// </summary>
        public static string StyleSheetValuePrompt {
            get {
                return ResourceManager.GetString("StyleSheetValuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subheading.
        /// </summary>
        public static string SubheadingFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("SubheadingFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority :.
        /// </summary>
        public static string TaxAuthoritySelectionLabel {
            get {
                return ResourceManager.GetString("TaxAuthoritySelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:.
        /// </summary>
        public static string ThicknessBottomLabel {
            get {
                return ResourceManager.GetString("ThicknessBottomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string ThicknessLeftLabel {
            get {
                return ResourceManager.GetString("ThicknessLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string ThicknessRightLabel {
            get {
                return ResourceManager.GetString("ThicknessRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string ThicknessTopLabel {
            get {
                return ResourceManager.GetString("ThicknessTopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Heading.
        /// </summary>
        public static string TitleHeadingFontsMenuItemHeader {
            get {
                return ResourceManager.GetString("TitleHeadingFontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottoms.
        /// </summary>
        public static string ToolTipAlignBottoms {
            get {
                return ResourceManager.GetString("ToolTipAlignBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Lefts.
        /// </summary>
        public static string ToolTipAlignLefts {
            get {
                return ResourceManager.GetString("ToolTipAlignLefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Rights.
        /// </summary>
        public static string ToolTipAlignRights {
            get {
                return ResourceManager.GetString("ToolTipAlignRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Tops.
        /// </summary>
        public static string ToolTipAlignTops {
            get {
                return ResourceManager.GetString("ToolTipAlignTops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        public static string ToolTipBringFront {
            get {
                return ResourceManager.GetString("ToolTipBringFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Horizontally.
        /// </summary>
        public static string ToolTipCenterHorizontally {
            get {
                return ResourceManager.GetString("ToolTipCenterHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Vertically.
        /// </summary>
        public static string ToolTipCenterVertically {
            get {
                return ResourceManager.GetString("ToolTipCenterVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ToolTipCopy {
            get {
                return ResourceManager.GetString("ToolTipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ToolTipCut {
            get {
                return ResourceManager.GetString("ToolTipCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Page Spacing.
        /// </summary>
        public static string ToolTipExpandLineSpace {
            get {
                return ResourceManager.GetString("ToolTipExpandLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow fonts.
        /// </summary>
        public static string ToolTipExpandPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipExpandPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Objects.
        /// </summary>
        public static string ToolTipGroupObjects {
            get {
                return ResourceManager.GetString("ToolTipGroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Horizontal Spacing Equal.
        /// </summary>
        public static string ToolTipHorizontalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipHorizontalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to next page.
        /// </summary>
        public static string ToolTipMoveToNextPage {
            get {
                return ResourceManager.GetString("ToolTipMoveToNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous page.
        /// </summary>
        public static string ToolTipMoveToPreviousPage {
            get {
                return ResourceManager.GetString("ToolTipMoveToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ToolTipNew {
            get {
                return ResourceManager.GetString("ToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolTipOpen {
            get {
                return ResourceManager.GetString("ToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ToolTipPaste {
            get {
                return ResourceManager.GetString("ToolTipPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ToolTipPrint {
            get {
                return ResourceManager.GetString("ToolTipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ToolTipRedo {
            get {
                return ResourceManager.GetString("ToolTipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Page Spacing.
        /// </summary>
        public static string ToolTipResetLineSpace {
            get {
                return ResourceManager.GetString("ToolTipResetLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset fonts to Style defaults.
        /// </summary>
        public static string ToolTipResetPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipResetPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolTipSave {
            get {
                return ResourceManager.GetString("ToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        public static string ToolTipSendBack {
            get {
                return ResourceManager.GetString("ToolTipSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Page Spacing.
        /// </summary>
        public static string ToolTipShrinkLineSpace {
            get {
                return ResourceManager.GetString("ToolTipShrinkLineSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink fonts.
        /// </summary>
        public static string ToolTipShrinkPageFontsSizes {
            get {
                return ResourceManager.GetString("ToolTipShrinkPageFontsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ToolTipUndo {
            get {
                return ResourceManager.GetString("ToolTipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Objects.
        /// </summary>
        public static string ToolTipUngroupObjects {
            get {
                return ResourceManager.GetString("ToolTipUngroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Vertical Spacing Equal.
        /// </summary>
        public static string ToolTipVerticalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipVerticalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TransformColor {
            get {
                object obj = ResourceManager.GetObject("TransformColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string TranslatorActivitiesLabel {
            get {
                return ResourceManager.GetString("TranslatorActivitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string TranslatorEmailLabel {
            get {
                return ResourceManager.GetString("TranslatorEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string TranslatorsTitle {
            get {
                return ResourceManager.GetString("TranslatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury.
        /// </summary>
        public static string TreasuryTitle {
            get {
                return ResourceManager.GetString("TreasuryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoMenuItemHeader {
            get {
                return ResourceManager.GetString("UndoMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Style defaults.
        /// </summary>
        public static string UseStyleDefaultsPrompt {
            get {
                return ResourceManager.GetString("UseStyleDefaultsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiters.
        /// </summary>
        public static string WaitersTitle {
            get {
                return ResourceManager.GetString("WaitersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the company title.
        /// </summary>
        public static string WriteCompanyTitlePrompt {
            get {
                return ResourceManager.GetString("WriteCompanyTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the title of menu hrading.
        /// </summary>
        public static string WriteMenuHeadingTitlePrompt {
            get {
                return ResourceManager.GetString("WriteMenuHeadingTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the description of menu item.
        /// </summary>
        public static string WriteMenuItemDescriptionPrompt {
            get {
                return ResourceManager.GetString("WriteMenuItemDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the extras of menu item.
        /// </summary>
        public static string WriteMenuItemExtrasPrompt {
            get {
                return ResourceManager.GetString("WriteMenuItemExtrasPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the full title of menu item.
        /// </summary>
        public static string WriteMenuItemFullTitlePrompt {
            get {
                return ResourceManager.GetString("WriteMenuItemFullTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the title of menu item.
        /// </summary>
        public static string WriteMenuItemTitlePrompt {
            get {
                return ResourceManager.GetString("WriteMenuItemTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write preparation statio description.
        /// </summary>
        public static string WritePreparationStationDescriptionPrompt {
            get {
                return ResourceManager.GetString("WritePreparationStationDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write  translator email.
        /// </summary>
        public static string WriteTranslatorEmailPrompt {
            get {
                return ResourceManager.GetString("WriteTranslatorEmailPrompt", resourceCulture);
            }
        }
    }
}
