//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashierStationDevice.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <MetaDataID>{42a7b479-f1e8-4780-a3c9-75c85ce6efb6}</MetaDataID>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashierStationDevice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CMOS Reset.
        /// </summary>
        public static string CMOSResetMessage
        {
            get
            {
                return ResourceManager.GetString("CMOSResetMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Κρίσιμο σφάλμα..
        /// </summary>
        public static string CriticalErrorMessage
        {
            get
            {
                return ResourceManager.GetString("CriticalErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Πρόβλημα επικοινωνίας με την συσκευή σήμανσης.
        /// </summary>
        public static string FiscalDeviceCommunicationErrorMessage
        {
            get
            {
                return ResourceManager.GetString("FiscalDeviceCommunicationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Φορολογική μνήμη σχεδόν γεμάτη.
        /// </summary>
        public static string FiscalMemoryAlmostFullMessage
        {
            get
            {
                return ResourceManager.GetString("FiscalMemoryAlmostFullMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Φορολογική μνήμη πλήρη.
        /// </summary>
        public static string FiscalMemoryOverflowMessage
        {
            get
            {
                return ResourceManager.GetString("FiscalMemoryOverflowMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Η συσκευή σήμανσης απάντησε με το εξής σφάλμα: Υπέρβαση χρονικού ορίου κλεισίματος Ζ.
        /// </summary>
        public static string FisicalDayOpenMessage
        {
            get
            {
                return ResourceManager.GetString("FisicalDayOpenMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Τέλος χαρτιού..
        /// </summary>
        public static string OutofPaperMessage
        {
            get
            {
                return ResourceManager.GetString("OutofPaperMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Πρόβλημα επικοινωνίας με το πρόγραμμα οδήγησης Samtec. Βεβαιωθείτε ότι βρίσκεται εν λειτουργία..
        /// </summary>
        public static string SamtecDriverConnectionErrorMessage
        {
            get
            {
                return ResourceManager.GetString("SamtecDriverConnectionErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingDialogTitle
        {
            get
            {
                return ResourceManager.GetString("SettingDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Η συσκευή είναι σε &quot;Χρήση μενού&quot;.
        /// </summary>
        public static string UserMenuModeMessage
        {
            get
            {
                return ResourceManager.GetString("UserMenuModeMessage", resourceCulture);
            }
        }
    }
}
