// This file was auto-generated by ML.NET Model Builder. 

using System;
using FlavourBusinessML.Model;

namespace FlavourBusinessML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                OnPreparationItemsResourceUnits = 87F,
                AvgTimeToComplete = 3F,
                PendingItemsResourceUnits = 120F,
                ItemResourceUnit = 27F,
                DefaultItemPreparationTime = 5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual ItemPreparationTime with predicted ItemPreparationTime from sample data...\n\n");
            Console.WriteLine($"OnPreparationItemsResourceUnits: {sampleData.OnPreparationItemsResourceUnits}");
            Console.WriteLine($"AvgTimeToComplete: {sampleData.AvgTimeToComplete}");
            Console.WriteLine($"PendingItemsResourceUnits: {sampleData.PendingItemsResourceUnits}");
            Console.WriteLine($"ItemResourceUnit: {sampleData.ItemResourceUnit}");
            Console.WriteLine($"DefaultItemPreparationTime: {sampleData.DefaultItemPreparationTime}");
            Console.WriteLine($"\n\nPredicted ItemPreparationTime: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
