//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorLayoutDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloorLayoutDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Table.
        /// </summary>
        public static string AddServicePointHeader {
            get {
                return ResourceManager.GetString("AddServicePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign service point.
        /// </summary>
        public static string AssignServicePointMenuItemHeader {
            get {
                return ResourceManager.GetString("AssignServicePointMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyMenuItemHeader {
            get {
                return ResourceManager.GetString("CopyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutMenuItemHeader {
            get {
                return ResourceManager.GetString("CutMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deassign service point.
        /// </summary>
        public static string DeassignServicePointMenuItemHeader {
            get {
                return ResourceManager.GetString("DeassignServicePointMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string DefaultServicePointDescription {
            get {
                return ResourceManager.GetString("DefaultServicePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Hall Layout.
        /// </summary>
        public static string DesignServiceAreaMenuContextHeader {
            get {
                return ResourceManager.GetString("DesignServiceAreaMenuContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabelMenuItemHeader {
            get {
                return ResourceManager.GetString("EditLabelMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuItemHeader {
            get {
                return ResourceManager.GetString("EditMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string FontsMenuItemHeader {
            get {
                return ResourceManager.GetString("FontsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label background.
        /// </summary>
        public static string HallLayoutLabelBkMenuItemHeader {
            get {
                return ResourceManager.GetString("HallLayoutLabelBkMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels Font.
        /// </summary>
        public static string HallLayoutLabelFontMenuItemHeader {
            get {
                return ResourceManager.GetString("HallLayoutLabelFontMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string HallLayoutMore {
            get {
                return ResourceManager.GetString("HallLayoutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadding....
        /// </summary>
        public static string LoadingPrompt {
            get {
                return ResourceManager.GetString("LoadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteMenuItemHeader {
            get {
                return ResourceManager.GetString("PasteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoMenuItemHeader {
            get {
                return ResourceManager.GetString("RedoMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service Area.
        /// </summary>
        public static string RemoveServiceAreaHeader {
            get {
                return ResourceManager.GetString("RemoveServiceAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Served meal types.
        /// </summary>
        public static string ServedMealTypesMenuContextHeader {
            get {
                return ResourceManager.GetString("ServedMealTypesMenuContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes label background.
        /// </summary>
        public static string ShapeLabelBackgroundTitlebarText {
            get {
                return ResourceManager.GetString("ShapeLabelBackgroundTitlebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes label fonts.
        /// </summary>
        public static string ShapeLabelFontsTitlebarText {
            get {
                return ResourceManager.GetString("ShapeLabelFontsTitlebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottoms.
        /// </summary>
        public static string ToolTipAlignBottoms {
            get {
                return ResourceManager.GetString("ToolTipAlignBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Lefts.
        /// </summary>
        public static string ToolTipAlignLefts {
            get {
                return ResourceManager.GetString("ToolTipAlignLefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Rights.
        /// </summary>
        public static string ToolTipAlignRights {
            get {
                return ResourceManager.GetString("ToolTipAlignRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Tops.
        /// </summary>
        public static string ToolTipAlignTops {
            get {
                return ResourceManager.GetString("ToolTipAlignTops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        public static string ToolTipBringFront {
            get {
                return ResourceManager.GetString("ToolTipBringFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Horizontally.
        /// </summary>
        public static string ToolTipCenterHorizontally {
            get {
                return ResourceManager.GetString("ToolTipCenterHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Vertically.
        /// </summary>
        public static string ToolTipCenterVertically {
            get {
                return ResourceManager.GetString("ToolTipCenterVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ToolTipCopy {
            get {
                return ResourceManager.GetString("ToolTipCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ToolTipCut {
            get {
                return ResourceManager.GetString("ToolTipCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolTipDelete {
            get {
                return ResourceManager.GetString("ToolTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Objects.
        /// </summary>
        public static string ToolTipGroupObjects {
            get {
                return ResourceManager.GetString("ToolTipGroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Horizontal Spacing Equal.
        /// </summary>
        public static string ToolTipHorizontalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipHorizontalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Same Height.
        /// </summary>
        public static string ToolTipMakeSameHeight {
            get {
                return ResourceManager.GetString("ToolTipMakeSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Same Size.
        /// </summary>
        public static string ToolTipMakeSameSize {
            get {
                return ResourceManager.GetString("ToolTipMakeSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Same Width.
        /// </summary>
        public static string ToolTipMakeSameWidth {
            get {
                return ResourceManager.GetString("ToolTipMakeSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ToolTipPaste {
            get {
                return ResourceManager.GetString("ToolTipPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ToolTipRedo {
            get {
                return ResourceManager.GetString("ToolTipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        public static string ToolTipSendBack {
            get {
                return ResourceManager.GetString("ToolTipSendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ToolTipUndo {
            get {
                return ResourceManager.GetString("ToolTipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Objects.
        /// </summary>
        public static string ToolTipUngroupObjects {
            get {
                return ResourceManager.GetString("ToolTipUngroupObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Vertical Spacing Equal.
        /// </summary>
        public static string ToolTipVerticalSpacingEqual {
            get {
                return ResourceManager.GetString("ToolTipVerticalSpacingEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string TreeNodeRenameMenuItemHeader {
            get {
                return ResourceManager.GetString("TreeNodeRenameMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoMenuItemHeader {
            get {
                return ResourceManager.GetString("UndoMenuItemHeader", resourceCulture);
            }
        }
    }
}
