//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourBusinessManager.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <MetaDataID>{93015fe6-fe1e-43ab-9c59-7317d7010ff4}</MetaDataID>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        /// <MetaDataID>{b45a3968-a475-417c-b3d9-4ac6ad561854}</MetaDataID>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <MetaDataID>{1ff726a0-544b-465f-a06e-4feeec17484a}</MetaDataID>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <MetaDataID>{d6723f5b-4e9b-448b-9571-d3fb79fb78d6}</MetaDataID>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <MetaDataID>{29e73500-538e-47b3-a707-e7b08c3643bf}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlavourBusinessManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <MetaDataID>{1f8761af-b635-467c-aa3d-1736435e391e}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The courier delayed his return.
        /// </summary>
        /// <MetaDataID>{89c904eb-c1e8-4dd1-ad6f-4c11b7c80dc7}</MetaDataID>
        internal static string CourierDelayedHisReturn
        {
            get
            {
                return ResourceManager.GetString("CourierDelayedHisReturn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier Station.
        /// </summary>
        /// <MetaDataID>{06d2abdc-7044-45aa-ada1-af59c09864cc}</MetaDataID>
        internal static string DefaultCashierStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultCashierStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courier.
        /// </summary>
        /// <MetaDataID>{b5b71c51-8b6f-46e2-b775-0f50fe4dbec5}</MetaDataID>
        internal static string DefaultCourierName
        {
            get
            {
                return ResourceManager.GetString("DefaultCourierName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        /// <MetaDataID>{96c05011-15fd-478f-a16a-a2b2fe5d4b3b}</MetaDataID>
        internal static string DefaultFiscalPartName
        {
            get
            {
                return ResourceManager.GetString("DefaultFiscalPartName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        /// <MetaDataID>{824b735a-ba16-45c2-a08b-255266bd0fd8}</MetaDataID>
        internal static string DefaultGraphicMenuName
        {
            get
            {
                return ResourceManager.GetString("DefaultGraphicMenuName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        /// <MetaDataID>{c23162bc-d25d-4962-891c-aabfdcd07a26}</MetaDataID>
        internal static string DefaultHallFileName
        {
            get
            {
                return ResourceManager.GetString("DefaultHallFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        /// <MetaDataID>{fa909efc-dd6e-4596-b854-897ac1f61ad8}</MetaDataID>
        internal static string DefaultHomeDeliveryCallCenterStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultHomeDeliveryCallCenterStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home Delivery.
        /// </summary>
        /// <MetaDataID>{80b28dcb-bd07-42f3-8bbd-82c19145ba10}</MetaDataID>
        internal static string DefaultHomeDeliveryServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultHomeDeliveryServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        /// <MetaDataID>{e23fbcae-4f65-4819-8b3f-ae39364caf7f}</MetaDataID>
        internal static string DefaultPaymentTerminalDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultPaymentTerminalDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparation Station.
        /// </summary>
        /// <MetaDataID>{34f70a23-4632-43c8-95ce-284d7665ea1f}</MetaDataID>
        internal static string DefaultPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        /// <MetaDataID>{6dcdc9a1-e949-4748-aae4-bdfcb2cde6de}</MetaDataID>
        internal static string DefaultPriceListDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultPriceListDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Hall.
        /// </summary>
        /// <MetaDataID>{8a31b4d3-f389-4519-8d97-a020b8c40d5a}</MetaDataID>
        internal static string DefaultServiceAreaDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        /// <MetaDataID>{899ba98a-a8d1-45c9-a2a0-5d8d8c74502f}</MetaDataID>
        internal static string DefaultServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        /// <MetaDataID>{863ce6fb-8b55-40d3-95d9-1eb7d08676db}</MetaDataID>
        internal static string DefaultSubPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultSubPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        /// <MetaDataID>{84433a3e-5f05-46df-a7dc-2d67f437a54d}</MetaDataID>
        internal static string DefaultSupervisorName
        {
            get
            {
                return ResourceManager.GetString("DefaultSupervisorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TakeAway POS.
        /// </summary>
        /// <MetaDataID>{e3337b55-d1fb-4ce3-a81c-093e968ed3b6}</MetaDataID>
        internal static string DefaultTakeAwayStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultTakeAwayStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiter.
        /// </summary>
        /// <MetaDataID>{da476452-ee2f-4ac4-91d1-cc2071061390}</MetaDataID>
        internal static string DefaultWaiterName
        {
            get
            {
                return ResourceManager.GetString("DefaultWaiterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DelayedClientsDecisionMessage
        {
            get
            {
                return ResourceManager.GetString("DelayedClientsDecisionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delay of order pick-up from the counter.
        /// </summary>
        /// <MetaDataID>{cccd532f-b06b-4a6d-85d0-2eb2982136fd}</MetaDataID>
        internal static string DelayedFoodshippingAtTheCounter
        {
            get
            {
                return ResourceManager.GetString("DelayedFoodshippingAtTheCounter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delay in shipment delivery.
        /// </summary>
        /// <MetaDataID>{e8fced3e-cfa6-498e-a59d-a725e02c2202}</MetaDataID>
        internal static string DelayedFoodshippingDelivery
        {
            get
            {
                return ResourceManager.GetString("DelayedFoodshippingDelivery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A storage named '{0}' already belongs to this storage..
        /// </summary>
        /// <MetaDataID>{03dc4dea-856d-49cb-83e5-6ce2f7e42113}</MetaDataID>
        internal static string DublicateStorageNameMessage
        {
            get
            {
                return ResourceManager.GetString("DublicateStorageNameMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        /// <MetaDataID>{f0eb3e40-53ed-40fb-87ee-25e02efc42ab}</MetaDataID>
        internal static string FlavoursServicePointDefaultName
        {
            get
            {
                return ResourceManager.GetString("FlavoursServicePointDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SessionDelaydConversetionMessage
        {
            get
            {
                return ResourceManager.GetString("SessionDelaydConversetionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table {0}.
        /// </summary>
        /// <MetaDataID>{e3888779-58b6-4448-a3e1-8b8ed94c3c94}</MetaDataID>
        internal static string TablePaymentDescription
        {
            get
            {
                return ResourceManager.GetString("TablePaymentDescription", resourceCulture);
            }
        }
    }
}
