//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourBusinessManager.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <MetaDataID>{f5812000-b4b5-4892-a931-2348bdc225d1}</MetaDataID>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        /// <MetaDataID>{54c166ce-2b0f-4b45-8762-b88e2319371b}</MetaDataID>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <MetaDataID>{285e0501-d598-4c76-998b-5115a4e1e9cd}</MetaDataID>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <MetaDataID>{010b8657-17da-4023-a38a-da14f8552334}</MetaDataID>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <MetaDataID>{be366474-633d-46ef-9639-99bad7c24e09}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlavourBusinessManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <MetaDataID>{4791c32e-3a42-45ff-9234-5ae42e60e5e8}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier Station.
        /// </summary>
        /// <MetaDataID>{390efd50-4016-4147-b4c7-c1d9cdca2249}</MetaDataID>
        internal static string DefaultCashierStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultCashierStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        /// <MetaDataID>{f77daa91-3a0f-4855-9a45-31e26310455f}</MetaDataID>
        internal static string DefaultFisicalPartName
        {
            get
            {
                return ResourceManager.GetString("DefaultFisicalPartName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        /// <MetaDataID>{729871bc-b45f-4755-9c51-679e92cf31e0}</MetaDataID>
        internal static string DefaultGraphicMenuName
        {
            get
            {
                return ResourceManager.GetString("DefaultGraphicMenuName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparation Station.
        /// </summary>
        /// <MetaDataID>{27625742-a90b-40e6-a16c-d56c9e17f4f7}</MetaDataID>
        internal static string DefaultPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Hall.
        /// </summary>
        /// <MetaDataID>{7398ace2-e5d8-454d-b6fa-7d662eb30dfe}</MetaDataID>
        internal static string DefaultServiceAreaDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        /// <MetaDataID>{d83e08f2-7683-4157-8c0f-500184bc1828}</MetaDataID>
        internal static string DefaultServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        /// <MetaDataID>{b70399d4-e33f-4935-bca5-669c15c380ac}</MetaDataID>
        internal static string DefaultSubPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultSubPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        /// <MetaDataID>{ee0457f3-9822-4de1-ac21-d9b2dd8c5a72}</MetaDataID>
        internal static string DefaultSupervisorName
        {
            get
            {
                return ResourceManager.GetString("DefaultSupervisorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TakeAway POS.
        /// </summary>
        /// <MetaDataID>{c00cd614-35a5-4de1-9fd2-f961e8db4b39}</MetaDataID>
        internal static string DefaultTakeAwayStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultTakeAwayStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiter.
        /// </summary>
        /// <MetaDataID>{cfa835c7-ab4b-47f7-a9ba-5df73f5f0eb9}</MetaDataID>
        internal static string DefaultWaiterName
        {
            get
            {
                return ResourceManager.GetString("DefaultWaiterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A storage named '{0}' already belongs to this storage..
        /// </summary>
        /// <MetaDataID>{39700948-ae0d-4437-ba87-595e15393d56}</MetaDataID>
        internal static string DublicateStorageNameMessage
        {
            get
            {
                return ResourceManager.GetString("DublicateStorageNameMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        /// <MetaDataID>{71cd34fc-e919-480c-8a1a-7487fd106342}</MetaDataID>
        internal static string FlavoursServicePointDefaultName
        {
            get
            {
                return ResourceManager.GetString("FlavoursServicePointDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table {0}.
        /// </summary>
        /// <MetaDataID>{070e23ad-4da5-4aaf-857e-43caee06b551}</MetaDataID>
        internal static string TablePaymentDescription
        {
            get
            {
                return ResourceManager.GetString("TablePaymentDescription", resourceCulture);
            }
        }
    }
}
