//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourBusinessManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        /// <MetaDataID>{11e64d8b-5934-4fd8-ac66-df462f3bc105}</MetaDataID>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <MetaDataID>{cd4fe1cc-8bad-4195-8412-e6df8f1e692a}</MetaDataID>
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <MetaDataID>{a9f60756-69da-457d-a56b-bb87d8bf2e62}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlavourBusinessManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <MetaDataID>{ae20fe53-ddb0-41dd-94a5-1f04ba72267d}</MetaDataID>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cashier Station.
        /// </summary>
        /// <MetaDataID>{427112ca-26c7-4b47-8404-2ef0213f4734}</MetaDataID>
        internal static string DefaultCashierStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultCashierStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        /// <MetaDataID>{aa87b870-bf58-4d8d-ab26-13cec6e07795}</MetaDataID>
        internal static string DefaultFisicalPartName
        {
            get
            {
                return ResourceManager.GetString("DefaultFisicalPartName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        /// <MetaDataID>{3c2192e0-72ef-4838-980d-3ef526ed8e48}</MetaDataID>
        internal static string DefaultGraphicMenuName
        {
            get
            {
                return ResourceManager.GetString("DefaultGraphicMenuName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparation Station.
        /// </summary>
        /// <MetaDataID>{8d87531b-a8ec-43c4-ae89-c3cc4dd422f6}</MetaDataID>
        internal static string DefaultPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Hall.
        /// </summary>
        /// <MetaDataID>{291bb860-bdb6-4d32-b504-4a2d5db746ba}</MetaDataID>
        internal static string DefaultServiceAreaDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServiceAreaDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        /// <MetaDataID>{8b1a4df8-94b7-4422-8ff2-c25fa2fec311}</MetaDataID>
        internal static string DefaultServicePointDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultServicePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        /// <MetaDataID>{5998e68c-e3ab-4771-a24e-1aa3695a2b30}</MetaDataID>
        internal static string DefaultSubPreparationStationDescription
        {
            get
            {
                return ResourceManager.GetString("DefaultSubPreparationStationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        /// <MetaDataID>{34d5ea19-67aa-4939-9f58-5d1a025952c8}</MetaDataID>
        internal static string DefaultSupervisorName
        {
            get
            {
                return ResourceManager.GetString("DefaultSupervisorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiter.
        /// </summary>
        /// <MetaDataID>{17b8370f-5b42-4c99-9938-1a24afe710d4}</MetaDataID>
        internal static string DefaultWaiterName
        {
            get
            {
                return ResourceManager.GetString("DefaultWaiterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A storage named '{0}' already belongs to this storage..
        /// </summary>
        /// <MetaDataID>{0fa5854c-2c5a-446c-b83f-f801402bceb6}</MetaDataID>
        internal static string DublicateStorageNameMessage
        {
            get
            {
                return ResourceManager.GetString("DublicateStorageNameMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        /// <MetaDataID>{0d03d02f-6538-4c68-9543-1c36778f913c}</MetaDataID>
        internal static string FlavoursServicePointDefaultName
        {
            get
            {
                return ResourceManager.GetString("FlavoursServicePointDefaultName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Table {0}.
        /// </summary>
        /// <MetaDataID>{3a539d9e-31f4-49bf-828c-846c8c3b3634}</MetaDataID>
        internal static string TablePaymentDescription
        {
            get
            {
                return ResourceManager.GetString("TablePaymentDescription", resourceCulture);
            }
        }
    }
}
